name: Deploy Validation Service Image

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker Image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      digest: ${{ steps.push.outputs.digest }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/mls-validation-service

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        id: push
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


  deploy_dev:
    name: Deploy image to dev
    runs-on: ubuntu-latest
    needs: push_to_registry
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        run: echo "pushing ${{ needs.push_to_registry.outputs.digest }} to dev"

  deploy_prod:
    name: Deploy image to prod
    runs-on: ubuntu-latest
    needs: deploy_dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        run: echo "pushing ${{ needs.push_to_registry.outputs.digest }} to prod"

  deploy_testnet:
    name: Deploy image to testnet
    runs-on: ubuntu-latest
    needs: push_to_registry
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        run: echo "pushing ${{ needs.push_to_registry.outputs.digest }} to testnet"